src/AppBundle/Entity/User.php
<?php
/**
 * Created by PhpStorm.
 * User: rachid
 * Date: 11/08/2018
 * Time: 10:28
 */
namespace AppBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="google_id", type="string", length=255, nullable=true)
     */
    protected $google_id;

    /**
     * @ORM\Column(name="google_access_token", type="string", length=255, nullable=true)
     */
    protected $google_access_token;

    /**
     * @ORM\Column(name="first_name", type="string", length=50, nullable=true)
     */
    protected $first_name;

    /**
     * @ORM\Column(name="last_name", type="string", length=50, nullable=true)
     */
    protected $last_name;

    /**
     * @ORM\Column(name="nb_connection", type="integer", nullable=true)
     */
    protected $nb_connection;

    public function __construct()
    {
        parent::__construct();
        $this->nb_connection = 1;
    }

    /**
     * @return mixed
     */
    public function getGoogleId()
    {
        return $this->google_id;
    }

    /**
     * @param mixed $google_id
     */
    public function setGoogleId($google_id)
    {
        $this->google_id = $google_id;
    }

    /**
     * @return mixed
     */
    public function getGoogleAccessToken()
    {
        return $this->google_access_token;
    }

    /**
     * @param $google_access_token
     */
    public function setGoogleAccessToken($google_access_token)
    {
        $this->google_access_token = $google_access_token;
    }

    /**
     * @return mixed
     */
    public function getFirstName()
    {
        return $this->first_name;
    }

    /**
     * @param mixed $first_name
     */
    public function setFirstName($first_name)
    {
        $this->first_name = $first_name;
    }

    /**
     * @return mixed
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * @param mixed $last_name
     */
    public function setLastName($last_name)
    {
        $this->last_name = $last_name;
    }

    /**
     * @return mixed
     */
    public function getNbConnection()
    {
        return $this->nb_connection;
    }

    /**
     * @param mixed $nb_connection
     */
    public function setNbConnection($nb_connection)
    {
        $this->nb_connection = $nb_connection;
    }


}

src/AppBundle/Controller/DefaultController.php
<?php

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends Controller
{
    /**
     * @Route("/homepage", name="homepage")
     */
    public function homeAction()
    {
        return $this->render('AppBundle:Default:show.html.twig');
    }

    /**
     * @Route("/")
     */
    public function indexAction()
    {
        return $this->render('AppBundle:Default:index.html.twig');
    }
}

src/AppBundle/Resources/views/Default/index.html.twig
{% extends "::base.html.twig" %}

{% block body %}
    <a href="{{ path('hwi_oauth_service_redirect', {'service': 'google' }) }}">Se connecter</a>

{% endblock %}

src/AppBundle/Resources/views/Default/show.html.twig
{% extends "::base.html.twig" %}

{% block body %}
    <a href="{{ path('fos_user_security_logout') }}">Logout</a>
    <p>{{ 'profile.show.username'|trans }}: {{ app.user.username }}</p>
    <p>{{ 'profile.show.email'|trans }}: {{ app.user.email }}</p>
    <p>{{ 'Activé' }}: {{ app.user.enabled ? 'Oui':'Non' }}</p>
    <p>{{ 'Google ID' }}: {{ app.user.googleId }}</p>
    <p>{{ 'Le token' }}: {{ app.user.googleAccessToken }}</p>
    <p>{{ 'Le mot de passe' }}: {{ app.user.password }}</p>
    <p>{{ 'La dernière authentification ' }}: {{ app.user.lastLogin|date('Y-m-d H:i:s')}}</p>
    <p>{{ 'Nombre de connexion' }}: {{ app.user.nbConnection}}</p>
{% endblock %}